### ISSUE TITLE
SPI HORIZONTAL版のUF2ファイル

### ISSUE THREAD

**Issue by KenKenMkIISR** [dozan5/pico_Xevious_lcd#3]
DOZANさん
ケンケンです。
ILI9341 SPI液晶のHORIZONTAL版を公開されたようですね。さっそく試してみたところNORMAL音声出力の音が小さくて、PWM版とファイルがどうやら同じでした。ぜひアップし直してください。

**Comment by dozan5** [comment]
ケンケン様
大変失礼しました。
Normal版のファイルをアップし直しました。

**Comment by KenKenMkIISR** [comment]
ありがとうございます。確認できました。
